%% ===================== SAVE DATASET =====================
% Cyclic time features
tDay    = timeofday(T);
tSecDay = seconds(tDay);
fracDay = tSecDay / (24*3600);
tod_sin = sin(2*pi*fracDay);
tod_cos = cos(2*pi*fracDay);

dayOfYear = day(T, "dayofyear");
fracYear  = (dayOfYear-1)/365;
doy_sin   = sin(2*pi*fracYear);
doy_cos   = cos(2*pi*fracYear);

% Build table: features + label
dataset = table( ...
    n_detected, ...
    snr_top1, snr_top3_mean, snr_median, snr_var, ...
    fd_abs_top1, fd_abs_top3_mean, fd_abs_std, ...
    snr_top1_slope, dfd_dt_top1, handover_rate_permin, ...
    tod_sin, tod_cos, doy_sin, doy_cos, ...
    trueMaxSlant_m, ...
    'VariableNames', { ...
    'n_detected', ...
    'snr_top1', 'snr_top3_mean', 'snr_median', 'snr_var', ...
    'fd_abs_top1', 'fd_abs_top3_mean', 'fd_abs_std', ...
    'snr_top1_slope', 'dfd_dt_top1', 'handover_rate_permin', ...
    'tod_sin', 'tod_cos', 'doy_sin', 'doy_cos', ...
    'trueMaxSlant_m' ...
    });

% Remove rows with NaN label (no satellites visible)
dataset = dataset(~isnan(dataset.trueMaxSlant_m), :);

% Save to CSV
outFile = "ephemeris_free_dataset.csv";
writetable(dataset, outFile);

fprintf("✅ Dataset saved to %s with %d samples and %d features+label.\n", ...
    outFile, height(dataset), width(dataset));
